//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6407
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        internal static string Bloqueado {
            get {
                return ResourceManager.GetString("Bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string btnAceptar {
            get {
                return ResourceManager.GetString("btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string btnBuscar {
            get {
                return ResourceManager.GetString("btnBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string btnCerrarSession {
            get {
                return ResourceManager.GetString("btnCerrarSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contáctanos.
        /// </summary>
        internal static string btnContPhone {
            get {
                return ResourceManager.GetString("btnContPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        internal static string btnCrear {
            get {
                return ResourceManager.GetString("btnCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grabar.
        /// </summary>
        internal static string btnGrabar {
            get {
                return ResourceManager.GetString("btnGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string btnIniPhone {
            get {
                return ResourceManager.GetString("btnIniPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politicas de Seguridad.
        /// </summary>
        internal static string btnPolSecure {
            get {
                return ResourceManager.GetString("btnPolSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicar.
        /// </summary>
        internal static string btnPublicar {
            get {
                return ResourceManager.GetString("btnPublicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrate.
        /// </summary>
        internal static string btnRegistrate {
            get {
                return ResourceManager.GetString("btnRegistrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genera RSS.
        /// </summary>
        internal static string btnRSS {
            get {
                return ResourceManager.GetString("btnRSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceder.
        /// </summary>
        internal static string btnStarSession {
            get {
                return ResourceManager.GetString("btnStarSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminos de Uso.
        /// </summary>
        internal static string btnTermUse {
            get {
                return ResourceManager.GetString("btnTermUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        internal static string btnVolver {
            get {
                return ResourceManager.GetString("btnVolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentado el.
        /// </summary>
        internal static string Comentado {
            get {
                return ResourceManager.GetString("Comentado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        internal static string Comentarios {
            get {
                return ResourceManager.GetString("Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deja tu Comentario.
        /// </summary>
        internal static string DejaTuComentario {
            get {
                return ResourceManager.GetString("DejaTuComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destacado.
        /// </summary>
        internal static string Destacado {
            get {
                return ResourceManager.GetString("Destacado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminado.
        /// </summary>
        internal static string Eliminado {
            get {
                return ResourceManager.GetString("Eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención.
        /// </summary>
        internal static string MnsAtencion {
            get {
                return ResourceManager.GetString("MnsAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Vigente.
        /// </summary>
        internal static string NoVigente {
            get {
                return ResourceManager.GetString("NoVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigente.
        /// </summary>
        internal static string Vigente {
            get {
                return ResourceManager.GetString("Vigente", resourceCulture);
            }
        }
    }
}
