//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Mensajes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hizo un comentario en.
        /// </summary>
        internal static string sMessage01 {
            get {
                return ResourceManager.GetString("sMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hizo el siguiente comentario.
        /// </summary>
        internal static string sMessage02 {
            get {
                return ResourceManager.GetString("sMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiere ser tu amigo.
        /// </summary>
        internal static string sMessage03 {
            get {
                return ResourceManager.GetString("sMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiere ser tu amigo, para responder a esta solicitud ingresa a .
        /// </summary>
        internal static string sMessage04 {
            get {
                return ResourceManager.GetString("sMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a confirmado tu solicitud de amistad.
        /// </summary>
        internal static string sMessage05 {
            get {
                return ResourceManager.GetString("sMessage05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificación de Consulta sitio :.
        /// </summary>
        internal static string sMessage06 {
            get {
                return ResourceManager.GetString("sMessage06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemos recibido su comentario, el cual será atendido a la brevedad..
        /// </summary>
        internal static string sMessage07 {
            get {
                return ResourceManager.GetString("sMessage07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a .
        /// </summary>
        internal static string sMessage08 {
            get {
                return ResourceManager.GetString("sMessage08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te damos la bienvenida a nuestro sitio, dsjgfvd g dfg dfg dfg d gdf gdfgdfgfdsgdfg fd g dfg df g dfsg dfsg dfsg dfgsdf.
        /// </summary>
        internal static string sMessage09 {
            get {
                return ResourceManager.GetString("sMessage09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo RSS generado..
        /// </summary>
        internal static string sMessage10 {
            get {
                return ResourceManager.GetString("sMessage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen datos para procesar..
        /// </summary>
        internal static string sMessage11 {
            get {
                return ResourceManager.GetString("sMessage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suscribirse a nuestro RSS.
        /// </summary>
        internal static string sMessage12 {
            get {
                return ResourceManager.GetString("sMessage12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguenos en Facebook.
        /// </summary>
        internal static string sMessage13 {
            get {
                return ResourceManager.GetString("sMessage13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguenos por Twitter.
        /// </summary>
        internal static string sMessage14 {
            get {
                return ResourceManager.GetString("sMessage14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos fueron registrados con exito..
        /// </summary>
        internal static string sMessage15 {
            get {
                return ResourceManager.GetString("sMessage15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se a producido un error al grabar, por favor intente nuevamente. Gracias..
        /// </summary>
        internal static string sMessage16 {
            get {
                return ResourceManager.GetString("sMessage16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje de Error.
        /// </summary>
        internal static string sMessage17 {
            get {
                return ResourceManager.GetString("sMessage17", resourceCulture);
            }
        }
    }
}
