//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ranking {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ranking() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Ranking", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes de realizar la calificación, debes tener en cuenta que el portal se reserva el derecho de eliminar calificaciones falsas o mal intencionadas. Debido a esto, debes considerar tu actitud, higiene personal, estado físico/mental, al momento de contactar o encontrate con la profesional..
        /// </summary>
        internal static string DesRanking {
            get {
                return ResourceManager.GetString("DesRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tú evaluación al servicio entregado por la profesional a quedado con Nota.
        /// </summary>
        internal static string lblMsgNotaOk {
            get {
                return ResourceManager.GetString("lblMsgNotaOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agradecemos tu participación calificando a la profesional. Podrás volver a realizar un clasificación a esta misma persona luego de pasados 10 días a partir de hoy..
        /// </summary>
        internal static string lblMsgOk {
            get {
                return ResourceManager.GetString("lblMsgOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        internal static string TituloRanking {
            get {
                return ResourceManager.GetString("TituloRanking", resourceCulture);
            }
        }
    }
}
