//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginUsers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginUsers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LoginUsers", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección correo electrónico.
        /// </summary>
        internal static string lblEmlOlvPwd {
            get {
                return ResourceManager.GetString("lblEmlOlvPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible en estos momentos enviar un enlace para restabecer tu  contraceña. Por favor intenta más tarde..
        /// </summary>
        internal static string lblErrOlvPwdResp {
            get {
                return ResourceManager.GetString("lblErrOlvPwdResp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envío no realizado..
        /// </summary>
        internal static string lblErrOlvPwdTtResp {
            get {
                return ResourceManager.GetString("lblErrOlvPwdTtResp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor introduce la dirección de correo electrónico que usaste para crear tu cuenta y te enviaremos un enlace para restablecer tu contraseña.
        /// </summary>
        internal static string lblMsnOlvPwd {
            get {
                return ResourceManager.GetString("lblMsnOlvPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te hemos enviado un mensaje por correo electrónico que te permitirá restablecer tu contraseña de manera rápida y fácil..
        /// </summary>
        internal static string lblMsnOlvPwdExitRsp {
            get {
                return ResourceManager.GetString("lblMsnOlvPwdExitRsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, revisa tu correo electrónico.
        /// </summary>
        internal static string lblMsnOlvPwdExitTt {
            get {
                return ResourceManager.GetString("lblMsnOlvPwdExitTt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviaremos un enlace para restablecer tu contraseña a esa dirección. Si has tenido problemas para recibir este enlace, por favor envianos un mensaje através de la zona contactenos del sitio..
        /// </summary>
        internal static string lblMsnOlvPwdResp {
            get {
                return ResourceManager.GetString("lblMsnOlvPwdResp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hemos podido encontrar ninguna cuenta en Paramours asociada con .
        /// </summary>
        internal static string lblNoExistePwd {
            get {
                return ResourceManager.GetString("lblNoExistePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Has olvidado tú contraseña?.
        /// </summary>
        internal static string lblOlvPassword {
            get {
                return ResourceManager.GetString("lblOlvPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar mi cuenta.
        /// </summary>
        internal static string lblRememberLogin {
            get {
                return ResourceManager.GetString("lblRememberLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login o Clave incorrecta, por favor vuelva a intentarlo..
        /// </summary>
        internal static string MsnLoggin01 {
            get {
                return ResourceManager.GetString("MsnLoggin01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene permisos de Administrador..
        /// </summary>
        internal static string MsnLoggin02 {
            get {
                return ResourceManager.GetString("MsnLoggin02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En estos momentos no podemos atenderlo, vuelva a intentarlo más tarde..
        /// </summary>
        internal static string MsnLoggin03 {
            get {
                return ResourceManager.GetString("MsnLoggin03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña?.
        /// </summary>
        internal static string ttlMsnOlvPwd {
            get {
                return ResourceManager.GetString("ttlMsnOlvPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave.
        /// </summary>
        internal static string txtPassword {
            get {
                return ResourceManager.GetString("txtPassword", resourceCulture);
            }
        }
    }
}
