//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Usuario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Usuario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Usuario", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        internal static string ApeUsuario {
            get {
                return ResourceManager.GetString("ApeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Solicitud de Amistad.
        /// </summary>
        internal static string btnConfirmarSolicitudAmistad {
            get {
                return ResourceManager.GetString("btnConfirmarSolicitudAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Solicitud de Amistad.
        /// </summary>
        internal static string BtnEnviarSolicitudAmistad {
            get {
                return ResourceManager.GetString("BtnEnviarSolicitudAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperando Confirmación de Amistad.
        /// </summary>
        internal static string BtnEsperandoConfirmacionAmistad {
            get {
                return ResourceManager.GetString("BtnEsperandoConfirmacionAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguir.
        /// </summary>
        internal static string BtnFollow {
            get {
                return ResourceManager.GetString("BtnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiendo.
        /// </summary>
        internal static string BtnFollowing {
            get {
                return ResourceManager.GetString("BtnFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Aceptar Solicitud.
        /// </summary>
        internal static string btnNoSolicitudAmistad {
            get {
                return ResourceManager.GetString("btnNoSolicitudAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Seguir.
        /// </summary>
        internal static string BtnUnFollow {
            get {
                return ResourceManager.GetString("BtnUnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga Fotos.
        /// </summary>
        internal static string CargaFotos {
            get {
                return ResourceManager.GetString("CargaFotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención!!!!, comunicamos que La profesional, aún no ha sido certificada por el equipo del portal..
        /// </summary>
        internal static string Certificado {
            get {
                return ResourceManager.GetString("Certificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave.
        /// </summary>
        internal static string ClaveUsuario {
            get {
                return ResourceManager.GetString("ClaveUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Básicos.
        /// </summary>
        internal static string DatosBasicos {
            get {
                return ResourceManager.GetString("DatosBasicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmlUsuario {
            get {
                return ResourceManager.GetString("EmlUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimado .
        /// </summary>
        internal static string Estimado {
            get {
                return ResourceManager.GetString("Estimado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fono.
        /// </summary>
        internal static string FonoUsuario {
            get {
                return ResourceManager.GetString("FonoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesional Certificada.
        /// </summary>
        internal static string IndCertificado {
            get {
                return ResourceManager.GetString("IndCertificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguidores.
        /// </summary>
        internal static string lblFollowers {
            get {
                return ResourceManager.GetString("lblFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginUsuario {
            get {
                return ResourceManager.GetString("LoginUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para crear tu nueva contraseña, por favor ingresarla en cada uno de los campos de más abajo.
        /// </summary>
        internal static string MsgIngNewPwd {
            get {
                return ResourceManager.GetString("MsgIngNewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has restablecido tu contraseña con éxito..
        /// </summary>
        internal static string MsnRstPwdResp {
            get {
                return ResourceManager.GetString("MsnRstPwdResp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebtControl.
        /// </summary>
        internal static string NomTipo1 {
            get {
                return ResourceManager.GetString("NomTipo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenciatario.
        /// </summary>
        internal static string NomTipo2 {
            get {
                return ResourceManager.GetString("NomTipo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mattel.
        /// </summary>
        internal static string NomTipo3 {
            get {
                return ResourceManager.GetString("NomTipo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitado.
        /// </summary>
        internal static string NomTipo4 {
            get {
                return ResourceManager.GetString("NomTipo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres.
        /// </summary>
        internal static string NomUsuario {
            get {
                return ResourceManager.GetString("NomUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa nueva clave.
        /// </summary>
        internal static string NuevaClaveUsuario {
            get {
                return ResourceManager.GetString("NuevaClaveUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de cliente (NkeyCliente).
        /// </summary>
        internal static string NumeroCliente {
            get {
                return ResourceManager.GetString("NumeroCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repita Clave.
        /// </summary>
        internal static string RepClaveUsuario {
            get {
                return ResourceManager.GetString("RepClaveUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reingresa nueva clave.
        /// </summary>
        internal static string RepNuevaClaveUsuario {
            get {
                return ResourceManager.GetString("RepNuevaClaveUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona / Categoría.
        /// </summary>
        internal static string TipoUsuario {
            get {
                return ResourceManager.GetString("TipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablece tu contraseña.
        /// </summary>
        internal static string TitRestPwd {
            get {
                return ResourceManager.GetString("TitRestPwd", resourceCulture);
            }
        }
    }
}
